# -*- coding: utf-8 -*-
"""Brain Tumor Detection System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvLJuoWjJeNSVjX1Afmrajew_1RejSCM
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d navoneel/brain-mri-images-for-brain-tumor-detection

!unzip brain-mri-images-for-brain-tumor-detection.zip

import os, shutil, pathlib
original_dir = pathlib.Path("brain_tumor_dataset")
base_dir = pathlib.Path("brain_tumor_small")
processed_dir = pathlib.Path("BrainTumor_224")

def make_subset(subset_name, files):
    for category in ["yes", "no"]:
        dest_dir = base_dir / subset_name / category
        os.makedirs(dest_dir, exist_ok=True)

        for file in files[category]:
            shutil.copy(file, dest_dir)

import random
random.seed(42)
files = {}
for category in ["yes", "no"]:
    all_files = list((original_dir / category).iterdir())
    random.shuffle(all_files)

    total = len(all_files)
    files[category] = {
        "train": all_files[:int(0.7 * total)],
        "validation": all_files[int(0.7 * total):int(0.85 * total)],
        "test": all_files[int(0.85 * total):]
    }

make_subset("train", {k: v["train"] for k, v in files.items()})
make_subset("validation", {k: v["validation"] for k, v in files.items()})
make_subset("test", {k: v["test"] for k, v in files.items()})

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode="nearest"
)

val_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

train_generator = train_datagen.flow_from_directory(
    "brain_tumor_small/train",
    target_size=(224,224),
    batch_size=16,
    class_mode="binary"
)

val_generator = val_datagen.flow_from_directory(
    "brain_tumor_small/validation",
    target_size=(224,224),
    batch_size=16,
    class_mode="binary"
)

class_weight = {0: 1.29, 1: 0.81}

base_model = EfficientNetB0(weights="imagenet", include_top=False, input_shape=(224,224,3))

base_model.trainable = False

from tensorflow.keras import layers, models, optimizers

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(1, activation="sigmoid")
])

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

checkpoint = ModelCheckpoint(
    "best_brain_model_phase1.keras",  # best model save hoga
    monitor="val_accuracy",
    save_best_only=True,
    verbose=1)
early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,   # agar 5 epochs tak improvement nahi, stop
    restore_best_weights=True,
    verbose=1)

callbacks_list = [checkpoint, early_stop]

history1 = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15,
    class_weight=class_weight
)

# After FineTuning
base_model.trainable = True
for layer in base_model.layers[:-20]:
    layer.trainable = False

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history2 = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10,
    class_weight=class_weight,
    callbacks=callbacks_list
)

model.save("brain_tumor_model.keras")

!pip install gradio tensorflow pillow

import gradio as gr
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input

model = load_model("brain_tumor_model.keras")

def predict_tumor(img):
    if img is None:
        return "No image", 0.0

    img = img.resize((224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)

    prediction = model.predict(img_array)[0][0]

    if prediction >= 0.5:
        label = "Tumor Detected"
        confidence = prediction * 100
    else:
        label = "No Tumor"
        confidence = (1 - prediction) * 100

    return label, round(confidence, 2)

interface = gr.Interface(
    fn=predict_tumor,
    inputs=gr.Image(type="pil", label="Upload Brain MRI"),
    outputs=[
        gr.Textbox(label="Prediction"),
        gr.Number(label="Confidence (%)")
    ],
    title="Brain Tumor Detection System (AI Powered)",
    description="Upload a brain MRI image to detect Tumor or No Tumor using Deep Learning.",
    theme="default"
)

interface.launch()



